export const homepageData: {id: number, title: string, subtitle: string, bgImage: string, leftButton: string, rightButton: string | null} [] = [
    {
        id: 1,
        title: 'Model 3',
        subtitle: 'Leasing starting at $399/mo',
        bgImage: 'model-3.jfif',
        leftButton: 'Custom Order',
        rightButton: 'Demo Drive',
    },
    {
        id: 2,
        title: 'Model Y',
        subtitle: '',
        bgImage: 'model-y.jfif',
        leftButton: 'Custom Order',
        rightButton: 'Demo Drive',
    },
    {
        id: 3,
        title: 'Model S',
        subtitle: '',
        bgImage: 'model-s.webp',
        leftButton: 'Custom Order',
        rightButton: 'Demo Drive',
    },
    {
        id: 4,
        title: 'Model X',
        subtitle: '',
        bgImage: 'model-x.webp',
        leftButton: 'Custom Order',
        rightButton: 'Demo Drive',
    },
    {
        id: 5,
        title: 'Solar Panels',
        subtitle: 'Lowest Cost Solar Panels in America',
        bgImage: 'solar-panels.jfif',
        leftButton: 'Order Now',
        rightButton: 'Learn More',
    },
    {
        id: 6,
        title: 'Solar Roof',
        subtitle: 'Produce Clean Energy From Your Roof',
        bgImage: 'solar-roof.webp',
        leftButton: 'Order Now',
        rightButton: 'Learn More',
    },
    {
        id: 7,
        title: 'Accessories',
        subtitle: '',
        bgImage: 'accessories.jfif',
        leftButton: 'Shop Now',
        rightButton: null,
    },
]